stages:
  - lint
  - sonarqube

sonarqube:
  stage:
    sonarqube
  tags:
    - sonarqube
  variables:
    GIT_DEPTH: "0"
  script:
    - sonar-scanner -D"sonar.projectKey=kms-cargonaut" -Dsonar.login=a9c8a840ff4254e520eeeac8eb54bf1fa20af045 -Dsonar.host.url=https://scm.thm.de/sonar
  only:
    - merge_requests
    - develop
    - master


# linter: node version on the gitlab.thm runner is to low (see description in ./info/pipeline
#lint:
#  stage: lint
#  image: node:lts
#  tags:
#    - nodejs
#    - npm
#  before_script:
#    - npm install eslint@latest
#  script:
#    - npx eslint .