stages:
  - install
  - build

setup-job 1/2:
  stage: install
  tags:
    - nodejs
    - npm
  script:
    - npm ci

setup-job 2/2:
  stage: build
  tags:
    - nodejs
    - npm
  script:
    - npm install -g @angular/cli
    - ng build --prod --base-href=/kms-todo/
