# Due to the outdated Node version and limited permissions on the thm.gitlab instance we decided
# to just keep Sonarqube running here -- so that at least one pipeline/job will be triggered.
# The other ci/cd jobs e.g. building, linting, testing are moved to another repo at github
# and can be triggered via a separate commit/push. See wiki for this.

stages:
  - sonarqube

sonarqube:
  stage:
    sonarqube
  tags:
    - sonarqube
  variables:
    GIT_DEPTH: "0"
  script:
    - sonar-scanner -D"sonar.projectKey=kms-cargonaut" -Dsonar.login=a9c8a840ff4254e520eeeac8eb54bf1fa20af045 -Dsonar.host.url=https://scm.thm.de/sonar
  only:
    - merge_requests
    - develop
    - master
